project_id = "yxdcngazogqmrffllbkl"

[functions.generate-sessions]
verify_jwt = true

[functions.calculate-tuition]
verify_jwt = true

[functions.compute-sibling-discounts]
verify_jwt = true

[functions.watch-sibling-threshold]
verify_jwt = true

[functions.post-payment]
verify_jwt = true

[functions.calculate-payroll]
verify_jwt = true

[functions.manage-admin-users]
verify_jwt = true

[functions.create-teacher]
verify_jwt = true

[functions.create-family]
verify_jwt = true

[functions.link-student-user]
verify_jwt = true

[functions.mark-attendance]
verify_jwt = true

[functions.reset-points]
verify_jwt = true

[functions.confirm-tuition]
verify_jwt = true

[functions.update-enrollment-rate]
verify_jwt = true

[functions.update-student-avatar]
verify_jwt = true

[functions.smart-family-payment]
verify_jwt = true

[functions.calculate-tuition-bulk]
verify_jwt = false

[functions.smart-dictation]
verify_jwt = true

[functions.pronounce-syllables]
verify_jwt = false

[functions.pronounce-viseme]
verify_jwt = false

[functions.image-search]
verify_jwt = false

[functions.word-enrichment]
verify_jwt = false

[functions.save-word]
verify_jwt = false

[functions.record-practice]
verify_jwt = false
